=== sfieten/Holodeck-B2B/main/certmanager/src/main/resources/xsd/hb2b-certmanager-cfg.xsd
<?xml version="1.0"?>
<!--
Copyright (C) 2017 The Holodeck B2B Team, Sander Fieten

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://holodeck-b2b.org/schemas/2019/09/config/certmanager"
    version="7.0.0" xmlns="http://holodeck-b2b.org/schemas/2019/09/config/certmanager">
    <xs:annotation>
        <xs:documentation>This XML schema defines the structure of the configuration file of the default <i>Certificate Manager</i> of Holodeck B2B.
        It configures the access to the three key stores of the Certificate Manager and includes two optional elements to configure OCSP revocation
        checks and "direct trust" in trading partner certificates.</xs:documentation>
        <xs:documentation>In version 7.0.0 the type attribute was added to the Password element to enable retrieving the password from a Java system 
        property or system environment variable.</xs:documentation>        
    </xs:annotation>
    <xs:element name="CertManagerConfiguration" type="CertManagerConfigurationType"/>
    <xs:complexType name="CertManagerConfigurationType">
        <xs:sequence>
        	<xs:element name="PerformRevocationCheck" type="xs:boolean" minOccurs="0" default="false">
        		<xs:annotation>
        			<xs:documentation>This OPTIONAL element indicates whether the Certificate Manager should perform a revocation check using OCSP when
        			 validating trust in a certificate (path). If the OSCP check cannot be performed, it will fall back to a regular validation without
        			 revocation check. This will be indicated as <i>"trusted with warnings"</i>.</xs:documentation>
        			 <xs:documentation>The default is value is <i>false</i> so the behaviour is the same as in earlier versions</xs:documentation>
        		</xs:annotation>
        	</xs:element>
        	<xs:element name="DirectTrustPartnerCertificates" type="xs:boolean" minOccurs="0" default="false">
        		<xs:annotation>
        			<xs:documentation>This OPTIONAL element indicates whether the Certificate Manager should use the trading partner certificate as
        			 as trust anchors when validating trust in a certificate (path). N</xs:documentation>
        			 <xs:documentation>The default value <i>false</i> results in the same behaviour as in version 4.x. Setting the value to <i>true</i>
        			 results in the same behaviour as in version 3 and before. The default is considered safer as the correct issuing of the certificates
        			 will be checked. </xs:documentation>
        		</xs:annotation>
        	</xs:element>        	
            <xs:element name="Keystores" type="KeystoresType">
                <xs:annotation>
                    <xs:documentation>This element contains the information needed to access the three JKS key stores used by Holodeck B2B's default Certificate Manager.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KeystoresType">
        <xs:sequence>
            <xs:element name="PrivateKeys" type="KeystoreAccessType">
                <xs:annotation>
                    <xs:documentation>The key store holding the private keys and related certificates that are used for signing and decrypting of messsages. 
                    Note that a key pair may need to contain more than  one certificate if a certificate chain needs to be included in a signature.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TradingPartnerCertificates" type="KeystoreAccessType">
                <xs:annotation>
                    <xs:documentation>The key store holding the certificates with the public keys used for encryption of messages.
                    Note that the certificates contained in this key store also act as "trust anchor" when "direct trust" is enabled.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="TrustedCertificates" type="KeystoreAccessType">
                <xs:annotation>
                    <xs:documentation>The key store holding "trust anchors" certificates used for trust validation of certificates used to sign messages.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="KeystoreAccessType">
        <xs:sequence>
            <xs:element name="Path" type="non-empty-string">
                <xs:annotation>
                    <xs:documentation>The path of the Java key store. A relative path is will start at the Holodeck B2B home directory (see org.holodeckb2b.interfaces.config.IConfiguration.getHolodeckB2BHome())</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element minOccurs="0" name="Password" type="PasswordType">
                <xs:annotation>
                    <xs:documentation>The password to access the key store. When the type attribute is set to "sys" or "env" the password is retrieved
                    from the runtime context, i.e. a Java system property ("sys") or operating system environment variable ("env"). The value of the
                    element in these cases must include the name of the property or environment variable to use.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PasswordType">
    	<xs:simpleContent>
    		<xs:extension base="non-empty-string">
				<xs:attribute name="type" default="literal">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="literal"/>
							<xs:enumeration value="sys"/>
							<xs:enumeration value="env"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
    		</xs:extension>
    	</xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="non-empty-string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:whiteSpace value="collapse"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== sfieten/Holodeck-B2B/distribution/basedir/conf/certmanager_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- =====================================================================================

             Holodeck B2B Default Certificate Manager Configuration

This file configures the access to the keystores used by the default implementation
of the Certificate Manager to store the key pairs and certificates needed in the 
processing of the messages. It uses three  JKS keystores which contain the keys and 
certificates needed in specific actions:
* The key pairs used for signing and decrypting messages. Note that a key pair may need to 
  contain more than one certificate if a certificate chain needs to be included in a 
  signature.
* The trading partner certificates with public keys used for encryption of messages and 
  identification.
* Holding "trust anchors" used for trust validation of certificates used to sign messages. 
  Normally these are the certificates of trusted Certificate Authorities. 

The use of these three key stores is similar to earlier versions of Holodeck B2B, but as 
in version 4 the trading partner certificates are by default not used during trust 
validation like they were in earlier versions. In version 4.x a so-called "compatibility 
mode" was offered so it could handle the configuration of earlier version. Since it can 
be useful in a environment where the certificates of trading partner are trusted this mode 
has now been replaced by a new <i>direct trust</i> configuration setting in which case the 
trading partner certificates are handled like trust anchors, with the exception that they 
are checked for validity. 
<p>Another new feature of this Certificate Manager is the option to perform a revocation 
check using OCSP on certificates. This check is disabled by default for back-ward 
compatibility and can be enabled in the configuration. Note however that when enabled and 
used in an environment where certificates don't provide OCSP information this will result 
in a lot of <code>ISignatureVerifiedWithWarning</code> events as the revocation check 
could not be executed.
===================================================================================== -->
<CertManagerConfiguration xmlns="http://holodeck-b2b.org/schemas/2019/09/config/certmanager"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://holodeck-b2b.org/schemas/2019/09/config/certmanager ../repository/xsd/hb2b-certmanager-cfg.xsd">
    <!--
    <PerformRevocationCheck>false</PerformRevocationCheck>
    <DirectTrustPartnerCertificates>false</DirectTrustPartnerCertificates>        
    -->
    <Keystores>
        <PrivateKeys>
            <Path>repository/certs/privatekeys.jks</Path>
            <Password>secrets</Password>
        </PrivateKeys>
        <TradingPartnerCertificates>
            <Path>repository/certs/partnerkeys.jks</Path>
            <Password>nosecrets</Password>
        </TradingPartnerCertificates>
        <TrustedCertificates>
            <Path>repository/certs/trustedcerts.jks</Path>
            <Password>trusted</Password>
        </TrustedCertificates>
    </Keystores>
</CertManagerConfiguration>
