=== sfieten/Holodeck-B2B/implementations/core/src/main/resources/xsd/workers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2014 The Holodeck B2B Team, Sander Fieten

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://holodeck-b2b.org/schemas/2012/12/workers"
  xmlns="http://holodeck-b2b.org/schemas/2012/12/workers"
  version="5.1.0">
  <xs:annotation>
    <xs:documentation>This XML schema specifies the XML representation of the configuration of a worker pool as used
     by the org.holodeckb2b.common.workerpool.XMLWorkerPoolConfigurator. </xs:documentation>
    <xs:documentation>The structure of the schema is the same as in earlier version in Holodeck B2B. As the worker pool
    name is since version 5.1.0 however set programmatically the name parameter is deprecated. Also the minimum number
    of workers is now zero as the configuration can be refreshed automatically during runtime. For the configuration of
    the automatic refresh a optional refresh parameter has been added.
    </xs:documentation>
  </xs:annotation>
  <xs:element name="workers">
    <xs:annotation>
      <xs:documentation>If the worker pool uses automatic refreshing of its configuration there is no minimum number of
       workers that must be configured as workers can be added later on. If the worker pool however is configured 
       statically it must contain at least one worker definition as it otherwise will quit immediately.
       </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="worker">
          <xs:annotation>
            <xs:documentation>The worker element contains the configuration of a specific worker in the pool and consist of five attributes and zero or more parameter child elements. The attributes are:
<ul>
<li>A REQUIRED name attribute of type xs:string that contains the name of this worker</li>
<li>A REQUIRED activate attribute of type xs:boolean which indicates if the worker be active</li>
<li>A OPTIONAL delay attribute of type xs:integer which contains the delay in seconds before starting the worker. If not specified the worker is started immediately.</li>
<li>A REQUIRED workerClass attribute of type xs:string that must contain the name of the class that implements the workers functionality</li>
<li>A OPTIONAL concurrent attribute of type xs:integer that indicates the number of concurrent executions</li>
<li>A OPTIONAL interval attribute of type xs:integer that defines the interval in seconds between repeated executions of the worker.
               If not included the worker will be executed just once. If set to 0 it will run continuously.</li>
</ul>
The parameter child elements can contain settings specific to the worker and consist of a name, value pair.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="parameter" type="parameter"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:NCName"/>
            <xs:attribute name="activate" use="required" type="xs:boolean"/>
            <xs:attribute name="delay" use="optional" default="0" type="xs:integer"/>
            <xs:attribute name="workerClass" use="required" type="xs:string"/>
            <xs:attribute name="concurrent" type="xs:integer"/>
            <xs:attribute name="interval" use="optional" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="poolName" type="xs:string">
	      <xs:annotation>
	      <xs:documentation>This attribute is <b>deprecated</b> and SHOULD NOT be used anymore. It will be ignored as
	      	the pool name is now set programmatically on instantiation of the pool</xs:documentation>	      
	      </xs:annotation>
      </xs:attribute>
      <xs:attribute name="refresh" type="xs:positiveInteger">
	      <xs:annotation>
	      <xs:documentation>This optional attribute defines the interval, in seconds, at which the configuration should
	      	be refreshed.</xs:documentation>	      
	      </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="parameter">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== sfieten/Holodeck-B2B/distribution/basedir/conf/workers.xml
<workers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://holodeck-b2b.org/schemas/2012/12/workers ../repository/xsds/workers.xsd"
 xmlns="http://holodeck-b2b.org/schemas/2012/12/workers"
>

    <!-- ==============================================================
    This worker is responsible for reading the P-Modes from file. It is
    part of the default implementation for P-Mode configuration that
    uses XML files to define the P-Modes with one file per P-Mode. For
    more information about configuring a P-Mode see the XSD that defines
    the P-Mode file (http://holodeck-b2b.org/schemas/2014/10/pmode).

    If you want to have a fixed set of P-Modes remove the interval
    attribute so the P-Modes are read only when Holodeck B2B is
    started. DO NOT de-activate this worker as it will prevent
    Holodeck B2B from starting correctly as P-Modes must be available
    to process messages!
    =============================================================== -->
    <worker name="pmodeWatcher" interval="20" activate="true"
        workerClass="org.holodeckb2b.common.pmode.PModeWatcher">
        <parameter name="watchPath">repository/pmodes</parameter>
    </worker>

    <!-- ==============================================================
    This worker is responsible for starting the message send process.
    Because the P-Modes need to be loaded before messages can be sent
    the start of the worker is delayed with 5 seconds to allow loading
    the P-Modes.
    NOTE that de-activating this worker will stop message sending!
    =============================================================== -->
    <worker name="senderWorker" interval="10" activate="true" delay="5"
        workerClass="org.holodeckb2b.core.workers.SenderWorker"/>

    <!-- ==============================================================
    This worker is responsible for checking whether a user message
    must be retransmitted because there was no timely Receipt.
    Because the P-Modes need to be loaded before messages can be retried
    the start of the worker is delayed with 10 seconds to allow loading
    the P-Modes.

    De-activating this worker will stop the retransmission function
    and therefore kill the AS4 Reception Awareness feature.
    =============================================================== -->
    <worker name="retransmissionWorker" interval="30" activate="true" delay="10"
        workerClass="org.holodeckb2b.core.receptionawareness.RetransmissionWorker"/>

    <!-- ==============================================================
    This worker is responsible for cleaning up information on old and
    processed messages, i.e. remove the meta-data information from the
    database and delete associated payloads from the file system.
    Through the optional "purgeAfterDays" parameter the number of days
    after which the message information should be removed can be set.
    If not specified 30 days is used as the default setting.
    =============================================================== -->
    <worker name="cleanupWorker" interval="3600" activate="true" delay="60"
        workerClass="org.holodeckb2b.core.workers.PurgeOldMessagesWorker"/>

    <!-- ==============================================================
    This worker is the default method for submitting messages to
    Holodeck B2B. It reads all message meta data documents from the
    specified directory and creates the messages for sending. The
    actual send process is started by the sender worker defined above.

    It is RECOMMENDED to specify an absolute path to the directory to
    watch for meta data documents.

    The worker will look for all files with ".mmd" extension. After
    processing the extension will be changed to ".processed". If an
    error occurs an new file with the same name but ".error" extension
    will be written with information about the error.

    Because the P-Modes need to be loaded before messages can be
    submitted the start of the worker is delayed with 5 seconds to
    allow loading the P-Modes.
    =============================================================== -->
    <worker name="submitFromFileWorker" interval="10" activate="true" delay="5"
        workerClass="org.holodeckb2b.backend.file.SubmitOperation">
        <parameter name="watchPath">data/msg_out</parameter>
    </worker>
    
 	<!-- ==============================================================
    This worker start the RMI server that enables the API for locally
    monitoring of the Holodeck B2B as implemented in the default  
    User Interface. The worker has one optional parameter "port" that 
    can be used to specify the port number that should be used by the
    RMI Server. The default port is set to 1701.
    =============================================================== -->
   <worker name="monitorAPI" activate="true" delay="10"
        workerClass="org.holodeckb2b.ui.api.RMIServer">
    </worker>   
</workers>

=== sfieten/Holodeck-B2B/main/core/src/test/resources/workerpoolcfg/wp_complete.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2014 The Holodeck B2B Team, Sander Fieten

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->
<workers xmlns="http://holodeck-b2b.org/schemas/2012/12/workers"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://holodeck-b2b.org/schemas/2012/12/workers ../../../main/resources/xsd/workers.xsd" 
 poolName="complete" refresh="5">
    <worker name="worker1" activate="false" workerClass="workerClass1">
       <parameter name="p1">value1</parameter>
       <parameter name="p2">value2</parameter>
       <parameter name="p3">value3</parameter>
       <parameter name="p4">value4</parameter>
    </worker>
    <worker name="worker2" activate="true" workerClass="workerClass2" concurrent="5" interval="30">
       <parameter name="p5">value5</parameter>
    </worker>
</workers>
